[package]
name = "ir"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0"
serde_json = "1.0"
oas3 = "0.20.0"
parser = { path = "../parser" }

[dev-dependencies]
pretty_assertions = "1.4.1"
